### PR TITLE
feat: update frezbo's signing keys

### PR DESCRIPTION
**Pull request by frezbo**
Update frezbo's (Noel Georgi) signing key after accidently resetting
offline YubiKey. Signature can be verified at:

- https://keyoxide.org/hkp/CC51116A94490FA6FB3C18EB2401FCAE863A06CA
- https://keys.openpgp.org/search?q=CC51116A94490FA6FB3C18EB2401FCAE863A06CA

Signed-off-by: Noel Georgi <git@frezbo.dev>

### CODE REVIEW

**Review by rsmitty — APPROVED** [review]

**Comment by smira** [comment]
we should probably keep old key as well, as you haven't lost it, it was destroyed, so any past signatures are still valid

**Comment by frezbo** [comment]
does talos-bot looks at old one, I haven't removed the old keys from github at all

**Comment by frezbo** [comment]
@smira moved the old to `frezbo.old.pgp`

**Comment by smira** [comment]
> does talos-bot looks at old one, I haven't removed the old keys from github at all

`talos-bot` doesn't look at it at all, `conform` looks at GitHub key. This repo is for offline checks (see the script).

**Pull request merged**
